title: Code, Canvas & Crescendo
email: noelalemwork@gmail.com
description: >- 
  Hi, my name is Noel Alemayehu and I am a software developer based in Addis Ababa, Ethiopia 
  specializing in backend, graphics and game development. 
  This blog is a place where I can put some of my random articles and experiments.
baseurl: ""
url: "http://noelnegash.github.io"
github_username:  NoelNegash

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
